version: "3"
services:
  pgsql_serv:
    image: postgres:9.6.6
    environment:
      POSTGRES_PASSWORD: '1234'
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - railsappnet
  railsserver:
    build: .
    depends_on:
      - pgsql_serv
    command:
      bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - railsappnet
networks:
  railsappnet:
volumes:
   pgdata: