default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: pgsql_serv
  username: postgres
  password: 1234

development:
  <<: *default
  database: workshop_dev

test:
  <<: *default
  database: workshop_test
